spring.application.name=fintrack
spring.datasource.url=jdbc:postgresql://localhost:5433/fintrackdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=ignored
spring.security.user.password=ignored